version: "3"

services:
  postgres-stock:
    image: postgres:13
    container_name: postgres-stock
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"